### ISSUE TITLE
Slides?

### ISSUE THREAD

**Issue by lurch** [janhak/bytecode#1]
Hi Jan,

I overheard somebody ask you if the slides from your (popular!) talk would be available, and I think you said you'd be adding them to this repo? (or at the very least, could there be a link to them from the README please?)

Cheers,
Andy

**Comment by janhak** [comment]
Andy, 

Absolutely. Sorry to be so slack about it. It is done now. 

Best Regards

Jan

**Comment by lurch** [comment]
Thanks. I hope your jaw is doing okay :)
